#!/usr/bin/env bash
SCRIPT_PATH="$HOME/setup-env"
if [[ -f "$SCRIPT_PATH/includes/vars.sh" ]]; then
	source "$SCRIPT_PATH/includes/vars.sh"
fi
main() {
	set -euo pipefail

	# Core tools

	sudo pacman -Sy --needed --noconfirm \
		zip unzip tar git curl base-devel linux-headers

	# Install yay if it doesn't exist

	if ! command -v yay >/dev/null 2>&1; then
		TMP_DIR=$(mktemp -d)
		git clone https://aur.archlinux.org/yay.git "$TMP_DIR"
		cd $TMP_DIR
		makepkg -si --noconfirm
	fi

	# Install uv
	if ! command -v uv >/dev/null 2>&1; then
		TMP_DIR=$(mktemp -d)
		curl -Ls https://astral.sh/uv/install.sh | sh
	fi

	# Install font
	FONTS_DIR="$HOME/.local/share/fonts"
	NERD_FONT_DIR="$FONTS_DIR/nerd-fonts"
	if [[ ! -d "$NERD_FONT_DIR" ]]; then
		mkdir -p "$NERD_FONT_DIR"
	fi

	install_font() {
		FONT_NAME="$1"
		FONT_DIR="$NERD_FONT_DIR/$FONT_NAME"
		FONT_ARCHIVE="$FONT_DIR/$FONT_NAME.tar.xz"
		FONT_URL="https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$FONT_NAME.tar.xz"

		if [[ -d "$FONT_DIR" ]]; then
			echo "$FONT_NAME already installed"
			return
		fi
		if [[ "$FONT_NAME" == "MapleMono" ]]; then
			FONT_URL="https://github.com/subframe7536/maple-font/releases/download/v7.9/MapleMono-NF-CN-unhinted.zip"
		fi
		mkdir -p "$FONT_DIR"

		echo "Downloading $FONT_NAME..."
		curl -fL "$FONT_URL" -o "$FONT_ARCHIVE"

		echo "Extracting..."
		(
			cd "$FONT_DIR" || exit 1
			tar -xf "$FONT_ARCHIVE"
			rm -f "$FONT_ARCHIVE"
		)

		fc-cache -fv 2 >/dev/null &>1
	}
	# Interactive mode for font install
	echo -e "${BGreen}Installing Fonts${Color_Off}"
	PS3="Select Font: "

	fonts=("JetBrainsMono" "MapleMono" "AdwaitaMono" "Iosevka")
	options=("${fonts[@]}" "ALl" "Exit")

	select opt in "${options[@]}"; do
		case $opt in
		"All")
			for font in "${fonts[@]}"; do
				install "$font"
			done
			break
			;;
		"Exit")
			break
			;;
		*)
			if [[ " ${fonts[*]} " =~ " $opt " ]]; then
				install_font "$opt"
				break
			else
				echo "Invalid choice"
			fi
			;;
		esac
	done

	# Install chezmoi (for dotfiles manager)
	if ! command chezmoi --version >/dev/null 2>&1; then
		sudo pacman -S chezmoi --noconfirm
	fi

	# Install konsave (to save or restore kde plasma configs)
	if ! command -v konsave >/dev/null 2>&1; then
		uv tool install konsave
	fi

	# Installing golang
	if ! command -v go >/dev/null 2>&1; then
		GolangVersion="1.26.1"
		GolangURL="https://golang.org/dl/go${GolangVersion}.linux-amd64.tar.gz"

		echo -e "${BGreen}Installing Golang ${GolangVersion}${Color_Off}"

		TMP_DIR=$(mktemp -d)
		ARCHIVE="$TMP_DIR/go${GolangVersion}.tar.gz"

		curl -fsL "$GolangURL" -o "$ARCHIVE"

		(
			cd "$TMP_DIR" || exit 1
			sudo tar -C /usr/local -xzf "$ARCHIVE"
			rm -f "$ARCHIVE"
		)
		# Logic to add env path for golang
		if [[ ! -d "$HOME/go/bin" ]]; then
			mkdir -p "$HOME/go/bin"
		fi
	fi

	# Installing rust
	if ! command -v cargo >/dev/null 2>&1; then
		curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
	fi
}

setup_env() {
	local TMP_DIR=$(mktemp -d)
	local target_home="$TMP_DIR"
	echo -e "${BGreen}Using HOME: ${target_home}${Color_Off}"
	# Creating env script injection
	mkdir -p "$target_home/.local"
	cat <<'EOF' >"$target_home/.local/env"
# Main logic to check if the path exist, if it does, stop adding to the path
add_path() {
	case ":$PATH:" in
	*:"$1":*) ;;
	*) export PATH="$1:$PATH" ;;
	esac
}

# Atuin
[[ -d "$target_home/.atuin/bin" ]] && add_path "$target_home/.atuin/bin"

# Golang
[[ -d "$target_home/go/bin" ]] && add_path "$target_home/go/bin"
[[ -d "/usr/local/go/bin" ]] && add_path "/usr/local/go/bin"

# Cargo/Rust
[[ -d "$target_home/.cargo/bin" ]] && add_path "$target_home/.cargo/bin"

# Setup-env (My project)
[[ -d "$target_home/setup-env" ]] && add_path "$target_home/setup-env"
[[ -d "$target_home/setup-env" ]] && add_path "$target_home/setup-env/interact"
EOF
	case "$SHELL" in
	*/zsh)
		CONFIG="$target_home/.zshrc"
		touch "$CONFIG"
		;;
	*/bash)
		CONFIG="$target_home/.bashrc"
		touch "$CONFIG"
		;;
	*)
		CONFIG="$target_home/.profile"
		touch "$CONFIG"
		;;
	esac
	if ! grep -xqF "source \"$target_home/.local/env\"" "$CONFIG"; then
		echo "source \"$target_home/.local/env\"" >>"$CONFIG"
	fi
	# Ensure current shell session can execute go/cargo
	source "$target_home/.local/env"
}
subcommand="${1:-}"
case "$subcommand" in
test)
	shift
	setup_env
	;;
*)
	if [[ $# -eq 0 ]]; then
		main
		exit 0
	fi
	;;
esac
